### ISSUE TITLE
Incubating repo is not accessible

### ISSUE THREAD

**Issue by liyimeng** [streamsets/helm-charts#3]
The incubating repo seem broken at the moment. 

`$ helm repo add streamsets-incubating https://streamsets.github.io/helm-charts/incubating
Error: Looks like "https://streamsets.github.io/helm-charts/incubating" is not a valid chart repository or cannot be reached: Failed to fetch https://streamsets.github.io/helm-charts/incubating/index.yaml : 404 Not Found`

**Comment by kunickiaj** [comment]
Fix this, and should be accessible now.
